### ISSUE TITLE
[init] Color 및 Theme 기초세팅

### ISSUE THREAD

**Issue by ThirFir** [SOPT-all/35-COLLABORATION-ANDROID-YES24TICKET#8]
## What is this issue? 🛠️
Color Token 설정
테마 적용
## Progress 🏃‍♀️
- [x] Color Token
- [x] 테마

**Comment by HAJIEUN02** [comment]
이슈에 Projects, Labels, milestone 설정하는 거 잊지 마세요! !

**Comment by ThirFir** [comment]
> 이슈에 Projects, Labels, milestone 설정하는 거 잊지 마세요! !

넵!!! 감사합니다 ㅎ_ㅎ
